version: "3.4"

services:

  postgres:
    image: postgres:10-alpine
    hostname: primary
    ports:
      - "5434:5432"
    environment:
      POSTGRES_DB: cookbook
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
